Add Closing conditions for pull requests
letsgamedev/Suffragium pull request #58
Opened 2022-06-30 09:30 UTC by letsgamedev

# Description
Habe einige Bedingungen hinzugefügt um das schließen von Pullrequests zu ermöglichen um so einen besseren Überblick gewährleisten zu können.

## Type of change
- [ ] Bug fix (non breaking change that fixes an issue)
- [x] New feature (non breaking change that adds functionality)
- [ ] Tooling (non breaking change that adds functionality to the workflow)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)

2022-06-30 14:16 UTC, b7g commented
It is not stated what happens to pull request older then 30 days that were in draft more (allowance 60 days) and then reopened (allowance 30 days).
The intent is not to delete them, right?

2022-06-30 16:48 UTC, Numenter commented
Maybe look at the last commit data and not at the creation date and just close inactive PRs/drafts

2022-06-30 17:13 UTC, b7g commented
I can predict Tom might want to easily see the PRs that can be closed in the overview, without going into every PR.
There is a search filter (the bar on top of the PRs) that can be used for that:

`updated:<2022-05-30`

this would display only PRs that had their last commit before the 30 May 2022

2022-07-01 07:59 UTC, Numenter commented
This would speed up the merge validation process. #59

2022-07-01 19:41 UTC, Numenter requested changes
Inactive and old are not the same. I would only close inactive PRs and lower the days to 20.
Maybe even lower. It can always be opened again.
#59 will make it easy to sort out inactive PRs.

2022-07-01 19:41 UTC, Numenter commented on CONTRIBUTING.md
> +- If a pull request is older than 60 days
```suggestion
If its true, the pull request / draft is considered as blocked and will be closed

- **Last commit is 20 days or older**
```

2022-07-03 17:49 UTC, RedstoneMedia commented
Maybe adding a clause that automatically closes PRs if they reach a certain dislike ratio after a shorter number of days (Maybe 3 ?) would also be a good idea.

2022-07-03 18:51 UTC, Numenter commented
Folks not only give dislikes because they don't like the PR. They dislike if the PR has flaws that they want to be fixed.
Its on the creator to consider, if he wants to edit the PR or to close it.
The forced closing is just to clean up after  abandoned PRs.
_Thats how i see it :P._

2022-07-04 11:02 UTC, letsgamedev commented
Ich habe den Vorschlag von Numenter angenommen dass nun der last commit entscheidend ist für das Schließungskriterium. Sollte es also ein PR nicht schaffen innerhalb von 20 Tagen (nach seinem letzten commit, achtung die Gefahr des künstlichen "Am Leben Haltens" ist gegeben durch Mini-commits) durchzusetzen, der PR geschlossen wird.

2022-07-04 15:46 UTC, merged